pull_request_rules:
  - name: Auto-merge for dependency bump pull requests
    conditions:
      - or:
          - author=dependabot[bot]
          - author=github-actions[bot]
          - author= ProverbialPennance
      - or:
          - label=dependencies
          - label=update
      - check-success=Build
      - check-success=Format
    actions:
      merge:
        method: rebase
