name: Flake

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  schedule:
    - cron: "0 12 * * 1"
  workflow_dispatch:

jobs:
  update:
    name: Flake Update
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v6

      - uses: DeterminateSystems/nix-installer-action@v22
        with:
          diagnostic-endpoint: ""

      - id: update-flake-lock
        uses: DeterminateSystems/update-flake-lock@v28
        with:
          commit-msg: "flake: update inputs"
          pr-title: "flake: update inputs"
          pr-labels: "dependencies"
          git-author-name: github-actions[bot]
          git-author-email: github-actions[bot]@users.noreply.github.com
